version: '3.7'

# To access data postgres, redis and rabbitmq writes within container from host machine
volumes:
  postgres_data: {}
  redis_data: {}
  rabbitmq_data: {}

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    image: proxycrawler_api
    depends_on:
      - postgres
      - redis
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./api:/var/www/proxycrawler/api

  crawler:
    image: proxycrawler_crawler
    build:
      context: ./crawler
      dockerfile: Dockerfile
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    depends_on:
      - postgres
      - redis
      - rabbitmq
    env_file: .env
    volumes:
      - ./crawler:/var/www/proxycrawler/crawler

  scheduler:
    image: proxycrawler_scheduler
    build:
      context: ./scheduler
      dockerfile: Dockerfile
      args:
        SCHEDULER_ENV: ${SCHEDULER_ENV:-development}
    depends_on:
      - rabbitmq
    env_file: .env
    volumes:
      - ./scheduler:/var/www/proxycrawler/scheduler
